/**
 * Category descriptions mapping to ensure labels are descriptive
 * even if the backend only returns the raw label code.
 */
const CATEGORY_DESCRIPTIONS = {
    "TEXT": "📰 Mixed Text: Mixtures of printed, handwritten, or typed text.",
    "TEXT_T": "📄 Typed: Machine-typed paragraphs.",
    "TEXT_P": "📄 Printed: Published paragraphs.",
    "TEXT_HW": "✏️📄 Handwritten: Handwritten paragraphs.",
    "LINE_T": "📏 Typed Table: Machine-typed tabular structure.",
    "LINE_P": "📏 Printed Table: Printed tabular structure.",
    "LINE_HW": "✏️📏 Handwritten Table: Handwritten tabular structure.",
    "DRAW": "📈 Drawing: Maps, paintings, schematics.",
    "DRAW_L": "📈📏 Structured Drawing: Drawings in a layout/legend.",
    "PHOTO": "🌄 Photo: Photographs.",
    "PHOTO_L": "🌄📏 Structured Photo: Photos in a table layout."
};

/**
 * Renders the prediction results into the DOM.
 * Handles both single image responses and multipage PDF responses.
 */
function renderResults(data) {
    const container = document.getElementById('results');
    container.innerHTML = '';

    if (!data) {
        container.innerHTML = `<div class="model-card" style="border-color: #ff9800; background-color: #fff3e0;">No data returned from server.</div>`;
        return;
    }

    if (data.error) {
         container.innerHTML = `<div class="model-card" style="border-color: #F44336; color: #721c24; background-color: #f8d7da;">Error: ${data.error}</div>`;
         return;
    }

    let html = `<h3>Results for: ${data.filename || 'Uploaded File'}</h3>`;
    html += `<p><strong>Model Version:</strong> ${data.model_version}</p>`;

    // --- Scenario 1: PDF Document (Multiple Pages) ---
    if (data.type === 'document' && data.pages) {
        data.pages.forEach(page => {
            html += `<div class="model-card">`;
            html += `<h4>Page ${page.page}</h4>`;

            // Display base64 thumbnail if generated by backend
            if (page.thumbnail) {
                html += `<img src="data:image/png;base64,${page.thumbnail}" alt="Page ${page.page} Thumbnail" style="max-height: 250px; display: block; margin-bottom: 1rem; border: 1px solid #eee;">`;
            }

            html += `<ul>`;
            page.predictions.forEach(pred => {
                const desc = CATEGORY_DESCRIPTIONS[pred.label] || pred.label;
                html += `<li class="prediction-item"><strong>${pred.label}</strong> - ${(pred.score * 100).toFixed(2)}% <br><small>${desc}</small></li>`;
            });
            html += `</ul></div>`;
        });
    }
    // --- Scenario 2: Single Image ---
    else if (data.type === 'image' && data.predictions) {
        html += `<div class="model-card"><ul>`;
        data.predictions.forEach(pred => {
            const desc = CATEGORY_DESCRIPTIONS[pred.label] || pred.label;
            html += `<li class="prediction-item"><strong>${pred.label}</strong> - ${(pred.score * 100).toFixed(2)}% <br><small>${desc}</small></li>`;
        });
        html += `</ul></div>`;
    }
    else {
        html += `<div class="model-card" style="border-color: #ff9800; background-color: #fff3e0;">Unexpected response format from the API.</div>`;
    }

    container.innerHTML = html;
}

// Execute on DOMContentLoaded
document.addEventListener('DOMContentLoaded', () => {
    const form = document.getElementById('classifyForm');
    const loader = document.getElementById('loader');
    const resultDiv = document.getElementById('results');

    if (form) {
        form.addEventListener('submit', async (e) => {
            e.preventDefault();

            resultDiv.innerHTML = '';
            loader.style.display = 'block';

            const formData = new FormData(form);
            const file = formData.get('file');

            // Basic check to route the endpoint
            let endpoint = '/predict_image';
            if (file && file.type === 'application/pdf') {
                endpoint = '/predict_document';
            }

            try {
                // IMPORTANT: Adjust the base URL if your FastAPI runs on a different host/port
                const baseUrl = window.location.origin.includes('localhost') ? 'http://localhost:8000' : '';

                const response = await fetch(`${baseUrl}${endpoint}`, {
                    method: 'POST',
                    body: formData
                });

                // Handle content-type parsing correctly
                const contentType = response.headers.get("content-type");
                if (!contentType || !contentType.includes("application/json")) {
                    throw new Error(`Invalid response type from server. Expected JSON.`);
                }

                if (!response.ok) {
                    const errJson = await response.json();
                    throw new Error(errJson.detail || `Server Error: ${response.statusText}`);
                }

                const data = await response.json();
                renderResults(data);

            } catch (err) {
                console.error(err);
                resultDiv.innerHTML = `<div class="model-card" style="border-color: #F44336; color: #721c24; background-color: #f8d7da;">
                    <strong>Error:</strong> ${err.message}
                </div>`;
            } finally {
                loader.style.display = 'none';
            }
        });
    } else {
        console.error("Form element 'classifyForm' not found!");
    }
});